### ISSUE TITLE
Missed implementation of data persistence layer

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry-holding/edgex-ui#2]
hi @badboy-huaqiao the [repository layer](https://github.com/edgexfoundry-holding/edgex-ui/tree/master/src/main/java/edgexfoundry/repository) seems has not been implemented yet?

**Comment by badboy-huaqiao** [comment]
you mean the User class ? yes, i have not started writing the code for the authorization module , you can see that in the AuthController.java file.
